name: Integration Test
on: [push]

jobs:
  build:
    environment: test

    runs-on: ubuntu-latest
    name: Build docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: mustardtech/build-docs-action@dev
        with:
          output_dir: output-docx

      - name: Upload docx Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-docx
          path: output-docx
          retention-days: 1

      - uses: mustardtech/build-docs-action@dev
        with:
          output_dir: output-pdf
          output_format: pdf

      - name: Upload pdf Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdf
          path: output-pdf
          retention-days: 1