name: Integration Test
on: [push]

jobs:
  build:
    environment: test

    runs-on: ubuntu-latest
    name: Build docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: mustardtech/build-docs-action@dev